version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
      dockerfile: Dockerfile
    image: rmsaj/udagram-reverseproxy:latest
  backend_user:
    build:
      context: ./udagram-api-user
    image: rmsaj/udagram-api-user
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: rmsaj/udagram-api-feed
  frontend:
    build:
      context: ./udagram-frontend
    image: rmsaj/udagram-frontend